name: action Workflow

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행
  pull_request:
    branches:
      - main # main 브랜치로의 PR이 열릴 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest # GitHub에서 제공하는 최신 Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 코드 체크아웃

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Node.js 16 버전 사용

      - name: Install dependencies
        run: npm install # 의존성 설치

      - name: Run tests
        run: npm test # 테스트 실행
